// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Checksum      []byte                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageRequest) Reset() {
	*x = StorageRequest{}
	mi := &file_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageRequest) ProtoMessage() {}

func (x *StorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageRequest.ProtoReflect.Descriptor instead.
func (*StorageRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *StorageRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *StorageRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StorageRequest) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

type RetrievalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievalRequest) Reset() {
	*x = RetrievalRequest{}
	mi := &file_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalRequest) ProtoMessage() {}

func (x *RetrievalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalRequest.ProtoReflect.Descriptor instead.
func (*RetrievalRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RetrievalRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type ChecksumVerification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checksum      []byte                 `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChecksumVerification) Reset() {
	*x = ChecksumVerification{}
	mi := &file_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChecksumVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChecksumVerification) ProtoMessage() {}

func (x *ChecksumVerification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChecksumVerification.ProtoReflect.Descriptor instead.
func (*ChecksumVerification) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ChecksumVerification) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RetrievalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *Response              `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievalResponse) Reset() {
	*x = RetrievalResponse{}
	mi := &file_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalResponse) ProtoMessage() {}

func (x *RetrievalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalResponse.ProtoReflect.Descriptor instead.
func (*RetrievalResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *RetrievalResponse) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *RetrievalResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Wrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Wrapper_Response
	//	*Wrapper_StorageReq
	//	*Wrapper_RetrievalReq
	//	*Wrapper_RetrievalResp
	//	*Wrapper_Checksum
	Msg           isWrapper_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wrapper) Reset() {
	*x = Wrapper{}
	mi := &file_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wrapper) ProtoMessage() {}

func (x *Wrapper) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wrapper.ProtoReflect.Descriptor instead.
func (*Wrapper) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Wrapper) GetMsg() isWrapper_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Wrapper) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Wrapper) GetStorageReq() *StorageRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_StorageReq); ok {
			return x.StorageReq
		}
	}
	return nil
}

func (x *Wrapper) GetRetrievalReq() *RetrievalRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RetrievalReq); ok {
			return x.RetrievalReq
		}
	}
	return nil
}

func (x *Wrapper) GetRetrievalResp() *RetrievalResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RetrievalResp); ok {
			return x.RetrievalResp
		}
	}
	return nil
}

func (x *Wrapper) GetChecksum() *ChecksumVerification {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_Checksum); ok {
			return x.Checksum
		}
	}
	return nil
}

type isWrapper_Msg interface {
	isWrapper_Msg()
}

type Wrapper_Response struct {
	Response *Response `protobuf:"bytes,1,opt,name=response,proto3,oneof"`
}

type Wrapper_StorageReq struct {
	StorageReq *StorageRequest `protobuf:"bytes,2,opt,name=storage_req,json=storageReq,proto3,oneof"`
}

type Wrapper_RetrievalReq struct {
	RetrievalReq *RetrievalRequest `protobuf:"bytes,3,opt,name=retrieval_req,json=retrievalReq,proto3,oneof"`
}

type Wrapper_RetrievalResp struct {
	RetrievalResp *RetrievalResponse `protobuf:"bytes,4,opt,name=retrieval_resp,json=retrievalResp,proto3,oneof"`
}

type Wrapper_Checksum struct {
	Checksum *ChecksumVerification `protobuf:"bytes,5,opt,name=checksum,proto3,oneof"`
}

func (*Wrapper_Response) isWrapper_Msg() {}

func (*Wrapper_StorageReq) isWrapper_Msg() {}

func (*Wrapper_RetrievalReq) isWrapper_Msg() {}

func (*Wrapper_RetrievalResp) isWrapper_Msg() {}

func (*Wrapper_Checksum) isWrapper_Msg() {}

var File_proto_messages_proto protoreflect.FileDescriptor

const file_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x14proto/messages.proto\"]\n" +
	"\x0eStorageRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\fR\bchecksum\"/\n" +
	"\x10RetrievalRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\"2\n" +
	"\x14ChecksumVerification\x12\x1a\n" +
	"\bchecksum\x18\x01 \x01(\fR\bchecksum\"4\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x11RetrievalResponse\x12\x1d\n" +
	"\x04resp\x18\x01 \x01(\v2\t.ResponseR\x04resp\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"\x99\x02\n" +
	"\aWrapper\x12'\n" +
	"\bresponse\x18\x01 \x01(\v2\t.ResponseH\x00R\bresponse\x122\n" +
	"\vstorage_req\x18\x02 \x01(\v2\x0f.StorageRequestH\x00R\n" +
	"storageReq\x128\n" +
	"\rretrieval_req\x18\x03 \x01(\v2\x11.RetrievalRequestH\x00R\fretrievalReq\x12;\n" +
	"\x0eretrieval_resp\x18\x04 \x01(\v2\x12.RetrievalResponseH\x00R\rretrievalResp\x123\n" +
	"\bchecksum\x18\x05 \x01(\v2\x15.ChecksumVerificationH\x00R\bchecksumB\x05\n" +
	"\x03msgB\fZ\n" +
	"./messagesb\x06proto3"

var (
	file_proto_messages_proto_rawDescOnce sync.Once
	file_proto_messages_proto_rawDescData []byte
)

func file_proto_messages_proto_rawDescGZIP() []byte {
	file_proto_messages_proto_rawDescOnce.Do(func() {
		file_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)))
	})
	return file_proto_messages_proto_rawDescData
}

var file_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_messages_proto_goTypes = []any{
	(*StorageRequest)(nil),       // 0: StorageRequest
	(*RetrievalRequest)(nil),     // 1: RetrievalRequest
	(*ChecksumVerification)(nil), // 2: ChecksumVerification
	(*Response)(nil),             // 3: Response
	(*RetrievalResponse)(nil),    // 4: RetrievalResponse
	(*Wrapper)(nil),              // 5: Wrapper
}
var file_proto_messages_proto_depIdxs = []int32{
	3, // 0: RetrievalResponse.resp:type_name -> Response
	3, // 1: Wrapper.response:type_name -> Response
	0, // 2: Wrapper.storage_req:type_name -> StorageRequest
	1, // 3: Wrapper.retrieval_req:type_name -> RetrievalRequest
	4, // 4: Wrapper.retrieval_resp:type_name -> RetrievalResponse
	2, // 5: Wrapper.checksum:type_name -> ChecksumVerification
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_messages_proto_init() }
func file_proto_messages_proto_init() {
	if File_proto_messages_proto != nil {
		return
	}
	file_proto_messages_proto_msgTypes[5].OneofWrappers = []any{
		(*Wrapper_Response)(nil),
		(*Wrapper_StorageReq)(nil),
		(*Wrapper_RetrievalReq)(nil),
		(*Wrapper_RetrievalResp)(nil),
		(*Wrapper_Checksum)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messages_proto_goTypes,
		DependencyIndexes: file_proto_messages_proto_depIdxs,
		MessageInfos:      file_proto_messages_proto_msgTypes,
	}.Build()
	File_proto_messages_proto = out.File
	file_proto_messages_proto_goTypes = nil
	file_proto_messages_proto_depIdxs = nil
}
